// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu_Uzb07uk9ei-ogE0RtVDB3XXhYUGNxg',
    appId: '1:793811082292:web:f71d2559140d5650d17e61',
    messagingSenderId: '793811082292',
    projectId: 'plandcorpapp',
    authDomain: 'plandcorpapp.firebaseapp.com',
    databaseURL: 'https://plandcorpapp-default-rtdb.firebaseio.com',
    storageBucket: 'plandcorpapp.appspot.com',
    measurementId: 'G-5LTX2780R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuIeQSbOc6Y6QCO2KB0o7JVvClnqqYCho',
    appId: '1:793811082292:android:d26768583aa05414d17e61',
    messagingSenderId: '793811082292',
    projectId: 'plandcorpapp',
    databaseURL: 'https://plandcorpapp-default-rtdb.firebaseio.com',
    storageBucket: 'plandcorpapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmBvq_RhxNhXlKp1MgkIJUdqCZ9CWu8Hc',
    appId: '1:793811082292:ios:a0993fbe57dba486d17e61',
    messagingSenderId: '793811082292',
    projectId: 'plandcorpapp',
    databaseURL: 'https://plandcorpapp-default-rtdb.firebaseio.com',
    storageBucket: 'plandcorpapp.appspot.com',
    iosClientId: '793811082292-j78cj87chbrs8vk4j4203un4nhi5du1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmBvq_RhxNhXlKp1MgkIJUdqCZ9CWu8Hc',
    appId: '1:793811082292:ios:a0993fbe57dba486d17e61',
    messagingSenderId: '793811082292',
    projectId: 'plandcorpapp',
    databaseURL: 'https://plandcorpapp-default-rtdb.firebaseio.com',
    storageBucket: 'plandcorpapp.appspot.com',
    iosClientId: '793811082292-j78cj87chbrs8vk4j4203un4nhi5du1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );
}
